
class mainPage:
    whatwedo_link = 'a[title="What we do"]'
    investorsLink = 'a[title="Investors"]'
    portfolioLink = 'a[title="Portfolio"]'
    teamLink = 'a[title="Team"]'
    newsLink = 'a[href="https://news.slateretailreit.com/"]'
    contactBtn = 'a[href="/popup/contact-us"]'
    signUpBtn = '.sign-up-form-news-letter-button a'
    allNewsBtn = 'a[class="all-news-button"]'
    closeBtn = '#cboxClose'
    contentList = '((//div[@class="item-list"])[2])//a'
    searchByName = 'input[id="edit-combine"]'
    filteredName = '//div[@class="team-info views-fieldset"]//div[@class="field-content"]/a'
    linksOnNewsPage = 'ul[id="bw-primary-links"]'
    unitInformation = 'a[href="#unit-information"]'
    presentations = 'a[href="#presentations"]'
    financialReports = 'div.nav-stick.stick > div > section#block-views-investors-block-1 > div > div > div > ul > li.views-row.views-row-3.views-row-odd > div > div > a'#'a[href="#financial-reports"]'
    distributions = 'a[href="#distributions"]'
    analystCoverage = 'a[href="#analyst-coverage"]'
    regulatoryFilings = 'a[href="#regulatory-filings"]'
    taxInformation = 'a[href="#tax-information"]'
    governance = 'a[href="#governance"]'
    committees = 'a[href="#committees"]'
    policies = 'a[href="#policies"]'
    furtherInformation = 'a[href="#further-information"]'
    list = '.nav-stick stick a'
    agreeCookie = 'input[value="OK, I agree"]'
    AcquisitionsDispositions = 'ul#bw-primary-links a[href="/acquisitions-dispositions"]'
    Appointment = 'ul#bw-primary-links a[href="/appointment"]'
    BoardofTrustees = 'ul#bw-primary-links a[href="/board-trustees"]'
    Distributions = 'ul#bw-primary-links a[href="/distributions"]'
    EquityOffering = 'ul#bw-primary-links a[href="/equity-offering"]'
    FinancialResults = 'ul#bw-primary-links a[href="/financial-results"]'
    Other = 'ul#bw-primary-links a[href="/other"]'
    Webcast = 'ul#bw-primary-links a[href="/webcast"]'
    state = '(//select[@title="State"])[2]'
    city= '(//input[@title="City"])[2]'
    sliderStart = '(//a[@class="ui-slider-handle ui-state-default ui-corner-all"])[1]'
    sliderEnd = '(//a[@class="ui-slider-handle ui-state-default ui-corner-all"])[2]'
    searchBtn= '#edit-submit-portfolio-summary-retail-'
    noOfProperties = 'div[class="view-header"]'
    teamLink = 'a[title="Team"]'
    newsLink = 'a[title="News"]'
    contactBtn = 'div[class="contact-us-button"]'
    signUpBtn = '//a[.="Sign up for our news alerts"]'
    termsLink = 'a[href="/terms-use"]'
    privacyPolicyLink = 'a[href="/privacy-policy"]'
    contactLink =  '.leaf a[href*="/contact-us"]'





