
class mainPage:
    whatwedo_link = 'a[title="What we do"]'
    investorsLink = 'a[title="Investors"]'
    portfolioLink = 'a[title="Portfolio"]'
    teamLink = 'a[title="Team"]'
    newsLink = 'a[href="https://news.slateretailreit.com/"]'
    contactBtn = 'a[href="/popup/contact-us"]'
    signUpBtn = '.sign-up-form-news-letter-button a'
    allNewsBtn = 'a[class="all-news-button"]'
    closeBtn = '#cboxClose'
    contentList = '((//div[@class="item-list"])[2])//a'
    searchByName = 'input[id="edit-combine"]'
    filteredName = '//div[@class="team-info views-fieldset"]//div[@class="field-content"]/a'
    linksOnNewsPage = 'ul[id="bw-primary-links"]'
    unitInformation = 'a[href="#unit-information"]'
    presentations = 'a[href="#presentations"]'
    financialReports = 'div.nav-stick.stick > div > section#block-views-investors-block-1 > div > div > div > ul > li.views-row.views-row-3.views-row-odd > div > div > a'#'a[href="#financial-reports"]'
    distributions = 'a[href="#distributions"]'
    analystCoverage = 'a[href="#analyst-coverage"]'
    regulatoryFilings = 'a[href="#regulatory-filings"]'
    taxInformation = 'a[href="#tax-information"]'
    governance = 'a[href="#governance"]'
    committees = 'a[href="#committees"]'
    policies = 'a[href="#policies"]'
    furtherInformation = 'a[href="#further-information"]'
    list = '.nav-stick stick a'
    agreeCookie = 'input[value="OK, I agree"]'
    AcquisitionsDispositions = 'a[href="#acquisitions-dispositions"]'
    Appointment = 'a[href="#appointment"]'
    BoardofTrustees = 'a[href="#board-trustees"]'
    Distributions = 'a[href="#distributions"]'
    EquityOffering = 'a[href="#equity-offering"]'
    FinancialResults = 'a[href="#financial-results"]'
    Other = 'a[href="#other"]'
    Webcast = 'a[href="#webcast"]'
    termsLink = '//a[.="Terms of Use"]'
    privacyPolicyLink = '//a[.="Privacy Policy"]'
    contactUsLink = '//a[.="Contact Us"]'

